name: kjede-b
on:
  workflow_run:
    workflows: ["kjede-a"]
    types: [completed]
jobs:
  ledd:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "B koeyrer. utloeyst av: ${{ github.event_name }}"
          date -u '+%H:%M:%S UTC'
          sleep 20
